### PR TITLE
object-manipulation-2 - Marvin Loreto

### PR DESCRIPTION
**Pull request by marvinloreto**
Screenshot (163)

### CODE REVIEW

**Comment by marvinloreto** [comment]
For my function defaults, I kept running into a linter error and couldn't figure out how to fix it.
Here is the code for that function:

function defaults(target, source) {
  for (var property in source) {

    if (!target.hasOwnProperty(property)) {
      target[property] = source[property];
    }
  }

}

**Comment by marvinloreto** [comment]
I am so sorry... I guess a lot went wrong and my string-manipulation-2 was added to this commit some how...

**Comment by marvinloreto** [comment]
Screenshot (164)

**Review by JenBowman1 — APPROVED** [review]
👍

**Pull request merged**
